# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(max_length=20),
        ),
    ]
