# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_auto_20171026_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
