# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 18:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20171027_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
