# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20171030_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user_name',
            new_name='user',
        ),
    ]
