# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0008_auto_20171030_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tweets.TwitterUser'),
        ),
    ]
