FROM python:3
ENV PYTHONUNBUFFERED 1

ADD . /backend

WORKDIR /backend

RUN /bin/bash -c "pip install -r ./requirements.txt"

RUN /bin/bash -c "python ./manage.py migrate"

CMD [ "/bin/bash", "-c", "python ./manage.py runserver 0.0.0.0:8000"]